# Save Files, images and more

In [3]:
import numpy as np
import matplotlib as plt


In [ ]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.random.rand(3, 3)
array3 = np.zeros([4, 4])

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
np.save('save/array1.npy', array1)
np.save('save/array2.npy', array2)
np.save('save/array3.npy', array3)

In [14]:
loded_array1 = np.load('save/array1.npy')
loded_array2 = np.load('save/array2.npy')
loded_array3 = np.load('save/array3.npy')
print(loded_array1)
print(loded_array2)
print(loded_array3)

[[1 2 3]
 [4 5 6]]
[[0.35299316 0.10181119 0.94824084]
 [0.24845267 0.72870154 0.89557163]
 [0.40315206 0.09637435 0.38811501]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
