# Save Files, images and more

In [5]:
import numpy as np


In [6]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.random.rand(3, 3)
array3 = np.zeros([4, 4])
array4 = np.ones([3, 3])

## Saves Array in increpted code

In [7]:
np.save('save/array1.npy', array1)
np.save('save/array2.npy', array2)
np.save('save/array3.npy', array3)
np.save('save/array4.npy', array4)

In [9]:
loded_array1 = np.load('save/array1.npy')
loded_array2 = np.load('save/array2.npy')
loded_array3 = np.load('save/array3.npy')
loded_array4 = np.load('save/array4.npy')
print(loded_array1)
print(loded_array2)
print(loded_array3)
print(loded_array4)

[[1 2 3]
 [4 5 6]]
[[0.89781937 0.08295075 0.75402306]
 [0.2166116  0.62298826 0.70017412]
 [0.74276875 0.36278243 0.23770267]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
