# Advance Operation With Business Example

In [19]:
import numpy as np
import matplotlib.pyplot as plt

In [20]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print(sales_data)
print("Shape of data: \n", sales_data.shape)
print("Sample data for first 3 restaurent: \n", sales_data[:3])
print("Sample data for first 3 restaurent: \n", sales_data[:, 0])

[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]
 [     4 180000 210000 240000 270000]
 [     5 160000 185000 205000 230000]]
Shape of data: 
 (5, 5)
Sample data for first 3 restaurent: 
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]
Sample data for first 3 restaurent: 
 [1 2 3 4 5]


In [21]:
# Total Sales per year
print(np.sum(sales_data, axis=0))

[     15  810000  945000 1085000 1240000]
