# Array Operations

In [131]:
import numpy as np

In [132]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print("Basic Slicing", arr[2:7])

print("With step", arr[2:8:2])

print("Nagetive Indexing", arr[-3])

Basic Slicing [3 4 5 6 7]
With step [3 5 7]
Nagetive Indexing 7


In [133]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(arr_2d)

print("Specific Element: ", arr_2d[1, 2])

print("Entire Row: ", arr_2d[2])

print("Entire Column: ", arr_2d[:, 1])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Specific Element:  6
Entire Row:  [7 8 9]
Entire Column:  [2 5 8]


## Sorting

In [134]:
unsorted = np.array([3, 2, 6, 5, 1, 4, 7, 9, 8])
print("Soreted Array: ", np.sort(unsorted))

array_2d = np.array([[3, 1],
                     [2, 1],
                     [2, 3]])
print(array_2d)

print("Sorted Column", np.sort(array_2d, axis=0))

print("Sorted Row", np.sort(array_2d, axis=1))

Soreted Array:  [1 2 3 4 5 6 7 8 9]
[[3 1]
 [2 1]
 [2 3]]
Sorted Column [[2 1]
 [2 1]
 [3 3]]
Sorted Row [[1 3]
 [1 2]
 [2 3]]


## Filter Array

In [135]:
Numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = Numbers[Numbers % 2 == 0]
print("Even Numbers: ", even_number)

Even Numbers:  [ 2  4  6  8 10]


## Filter With Mask

In [136]:
mask = Numbers > 5
print("Numbers greter than 5: ", Numbers[mask])

Numbers greter than 5:  [ 6  7  8  9 10]


## Fancy Indexing Vs np.where()

In [137]:
indices = [0, 2, 4]
print(Numbers[indices])

where_result = np.where(Numbers > 5)
print(Numbers[where_result])

[1 3 5]
[ 6  7  8  9 10]


In [138]:
condition_array = np.where(Numbers > 5, Numbers*2, Numbers)
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


## Adding and Removing Data

In [139]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


## Array Compatibility

In [140]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print("Compatibility Shape: ", a.shape == b.shape)

Compatibility Shape:  True


In [141]:
original = np.array([[1, 2],
                     [3, 4]])
new_row = np.array([5, 6])

with_new_row = np.vstack((original, new_row))
print(original, "\n")
print(with_new_row)

new_col = np.array(([8], [7]))
with_new_col = np.hstack((original, new_col))
print(with_new_col)

[[1 2]
 [3 4]] 

[[1 2]
 [3 4]
 [5 6]]
[[1 2 8]
 [3 4 7]]


## Delete In Array

In [ ]:
darr = np.array([1, 2, 3, 4, 5])
delete = np.delete(darr, 2)

print("Deleted: ", delete)
print(darr)

Deleted:  [1 2 4 5]
[1 2 3 4 5]
