# Creating array from scratch

In [51]:
import numpy as np

zeros = np.zeros((3, 4))
print("Zeros Array: \n", zeros)



Zeros Array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [52]:
ones = np.ones((2, 3))
print("Ones Array: \n", ones)

Ones Array: 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [53]:
full = np.full((3, 3), 7)
print(full)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [54]:
random = np.random.random((3,3))
print(random)

[[0.69244134 0.2102028  0.77380864]
 [0.7773961  0.85381101 0.93774499]
 [0.43594706 0.61518001 0.84424716]]


In [55]:
sequence = np.arange(0, 20, 2)
print(sequence)

[ 0  2  4  6  8 10 12 14 16 18]


### Vector, Matrix and Vector

In [56]:
vector = np.array([1, 2, 3, 4])
print(vector)

[1 2 3 4]


In [57]:
Matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print(Matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [58]:
tensor = np.array([[[1, 2], [2, 3]],
                    [[5, 6], [6, 7]]])
print(tensor)

[[[1 2]
  [2 3]]

 [[5 6]
  [6 7]]]


### Array Properties

In [59]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
print("shape:", arr.shape)
print("daimenstion:", arr.ndim)
print("size:", arr.size)
print("data type: ", arr.dtype)

shape: (3, 3)
daimenstion: 2
size: 9
data type:  int64


### Array Reshaping

In [75]:
array = np.arange(0, 15)
print("Original Array: ", array)

reshaped = array.reshape((3, 5))
print(reshaped)

flattended = reshaped.flatten()
print(flattended)

# Return view, instend of copy
raveld = reshaped.ravel()
print(raveld)

# Transpose
transpose = reshaped.T
print(transpose)

Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
